#📌 Extracción

In [62]:
import pandas as pd
import numpy as np

## Primero se debe Cargar los datos directamente desde la gtihub utilizando Python.

In [83]:
# URL de la API que devuelve JSON
url = 'https://raw.githubusercontent.com/AngieNaranjoD/TelecomX_Alura/refs/heads/main/TelecomX_Data.json'
datos_telecomx = pd.read_json(url)

## Conoce el conjunto de datos

### Diccionario de datos

*   customerID: número de identificación único de cada cliente
*   Churn: si el cliente dejó o no la empresa/n
*   gender: género (masculino y femenino)/n
*   SeniorCitizen: información sobre si un cliente tiene o no una edad igual o mayor a 65 años
*   Partner: si el cliente tiene o no una pareja
*   Dependents: si el cliente tiene o no dependientes
*   tenure: meses de contrato del cliente
*   PhoneService: suscripción al servicio telefónico
*   MultipleLines: suscripción a más de una línea telefónica
*   InternetService: suscripción a un proveedor de internet
*   OnlineSecurity: suscripción adicional de seguridad en línea
*   OnlineBackup: suscripción adicional de respaldo en línea
*   DeviceProtection: suscripción adicional de protección del dispositivo
*   TechSupport: suscripción adicional de soporte técnico, menor tiempo de espera
*   StreamingTV: suscripción de televisión por cable
*   StreamingTV: suscripción de televisión por cable
*   xContract: tipo de contrato
*   xContract: tipo de contrato
*   xPaymentMethod: forma de pago
*   Charges.Monthly: total de todos los servicios del cliente por mes
*   Charges.Total: total gastado por el cliente

In [69]:
datos_telecomx.head(10)

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
5,0013-MHZWF,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
6,0013-SMEOE,No,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7,0014-BMAQU,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Two year', 'PaperlessBilling': '..."
8,0015-UOCOJ,No,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
9,0016-QLJIS,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [70]:
datos_telecomx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [10]:
datos_telecomx.dtypes

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

## Normalizando los datos

1. `df.to_dict(orient="records")` convierte el DataFrame a una lista de diccionarios Python reales
2. Durante esta conversión, esas strings se evalúan como diccionarios Python
3. `pd.json_normalize()` puede entonces aplanar correctamente estas estructuras anidadas.

In [84]:
df_normalizado3 = pd.json_normalize(datos_telecomx)
df_normalizado3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Empty DataFrame

In [14]:
df_normalizado = pd.json_normalize(datos_telecomx.to_dict(orient='records'))
df_normalizado

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [32]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [71]:
from pandas import json_normalize

In [79]:
df_normalizado3 = pd.json_normalize(datos_telecomx)
df_normalizado3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Empty DataFrame

In [78]:
df_normalizado3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Empty DataFrame

### Otra forma de normalizar los datos podría ser:

In [29]:
# Crear DataFrame inicial con las columnas simples
df_base = datos_telecomx[['customerID', 'Churn']].copy()

In [21]:
# Normalizar datos anidados de 'customer'
customer_df = pd.json_normalize(datos_telecomx['customer'])
customer_df.columns = ['customer_' + col for col in customer_df.columns]

In [22]:
# Normalizar datos anidados de 'phone'
phone_df = pd.json_normalize(datos_telecomx['phone'])
phone_df.columns = ['phone_' + col for col in phone_df.columns]

In [23]:
# Normalizar datos anidados de 'internet'
internet_df = pd.json_normalize(datos_telecomx['internet'])
internet_df.columns = ['internet_' + col for col in internet_df.columns]

In [24]:
# Normalizar datos anidados de 'account' (incluyendo charges anidados)
account_df = pd.json_normalize(datos_telecomx['account'])
# Renombrar columnas para mayor claridad
account_df.columns = [
    col.replace('Charges.', 'account_charges_') if 'Charges.' in col
    else 'account_' + col
    for col in account_df.columns
]

In [30]:
# Combinar todos los DataFrames
df_final = pd.concat([df_base, customer_df, phone_df, internet_df, account_df], axis=1)
df_final.sample()

,customerID,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,phone_PhoneService,phone_MultipleLines,internet_InternetService,...,internet_OnlineBackup,internet_DeviceProtection,internet_TechSupport,internet_StreamingTV,internet_StreamingMovies,account_Contract,account_PaperlessBilling,account_PaymentMethod,account_charges_Monthly,account_charges_Total
227,0337-CNPZE,Yes,Female,0,No,No,41,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,106.3,4443.45

In [31]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer_gender            7267 non-null   object
 3   customer_SeniorCitizen     7267 non-null   int64
 4   customer_Partner           7267 non-null   object
 5   customer_Dependents        7267 non-null   object
 6   customer_tenure            7267 non-null   int64
 7   phone_PhoneService         7267 non-null   object
 8   phone_MultipleLines        7267 non-null   object
 9   internet_InternetService   7267 non-null   object
 10  internet_OnlineSecurity    7267 non-null   object
 11  internet_OnlineBackup      7267 non-null   object
 12  internet_DeviceProtection  7267 non-null   object
 13  internet_TechSupport       7267 non-null   object
 14  internet_StreamingTV       7267 non-null   object
 15  internet_StreamingMovies   7267 non-null   object
 16  account_Contract           7267 non-null   object
 17  account_PaperlessBilling   7267 non-null   object
 18  account_PaymentMethod      7267 non-null   object
 19  account_charges_Monthly    7267 non-null   float64
 20  account_charges_Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

## Comprobación de incoherencias en los datos

**Acciones más comunes**

*   Duplicados
*   Valores vacíos
*   Valores Nulos
*   Tipos de datos
*   Valores atípicos
*   Consistencia y validez de los datos categóricos
*   Normalización de textos

In [56]:
df_final.shape

(7267, 21)

### Para no hacer la verificación de valores unicos uno a uno, es mejor hacerlo con un loop.

In [60]:
print("VALORES ÚNICOS POR COLUMNA\n")

for columna in df_final.columns:
    unicos = pd.unique(df_final[columna])
    print(f"{columna}:")
    print(f"  Cantidad únicos: {len(unicos)}")
    print(f"  Valores: {unicos}")
    print("-" * 50)

VALORES ÚNICOS POR COLUMNA

customerID:
  Cantidad únicos: 7267
  Valores: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
--------------------------------------------------
Churn:
  Cantidad únicos: 3
  Valores: ['No' 'Yes' '']
--------------------------------------------------
customer_gender:
  Cantidad únicos: 2
  Valores: ['Female' 'Male']
--------------------------------------------------
customer_SeniorCitizen:
  Cantidad únicos: 2
  Valores: [0 1]
--------------------------------------------------
customer_Partner:
  Cantidad únicos: 2
  Valores: ['Yes' 'No']
--------------------------------------------------
customer_Dependents:
  Cantidad únicos: 2
  Valores: ['Yes' 'No']
--------------------------------------------------
customer_tenure:
  Cantidad únicos: 73
  Valores: [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
--------------------------------------------------
phone_PhoneService:
  Cantidad únicos: 2
  Valores: ['Yes' 'No']
--------------------------------------------------
phone_MultipleLines:
  Cantidad únicos: 3
  Valores: ['No' 'Yes' 'No phone service']
--------------------------------------------------
internet_InternetService:
  Cantidad únicos: 3
  Valores: ['DSL' 'Fiber optic' 'No']
--------------------------------------------------
internet_OnlineSecurity:
  Cantidad únicos: 3
  Valores: ['No' 'Yes' 'No internet service']
--------------------------------------------------
internet_OnlineBackup:
  Cantidad únicos: 3
  Valores: ['Yes' 'No' 'No internet service']
--------------------------------------------------
internet_DeviceProtection:
  Cantidad únicos: 3
  Valores: ['No' 'Yes' 'No internet service']
--------------------------------------------------
internet_TechSupport:
  Cantidad únicos: 3
  Valores: ['Yes' 'No' 'No internet service']
--------------------------------------------------
internet_StreamingTV:
  Cantidad únicos: 3
  Valores: ['Yes' 'No' 'No internet service']
--------------------------------------------------
internet_StreamingMovies:
  Cantidad únicos: 3
  Valores: ['No' 'Yes' 'No internet service']
--------------------------------------------------
account_Contract:
  Cantidad únicos: 3
  Valores: ['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
account_PaperlessBilling:
  Cantidad únicos: 2
  Valores: ['Yes' 'No']
--------------------------------------------------
account_PaymentMethod:
  Cantidad únicos: 4
  Valores: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
account_charges_Monthly:
  Cantidad únicos: 1585
  Valores: [65.6  59.9  73.9  ... 91.75 68.8  67.85]
--------------------------------------------------
account_charges_Total:
  Cantidad únicos: 6531
  Valores: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']
--------------------------------------------------

                      Columna  Valores_Unicos Tipo_Dato  Valores_Nulos  \
0                  customerID            7267    object              0
1                       Churn               3    object              0
2             customer_gender               2    object              0
3      customer_SeniorCitizen               2     int64              0
4            customer_Partner               2    object              0
5         customer_Dependents               2    object              0
6             customer_tenure              73     int64              0
7          phone_PhoneService               2    object              0
8         phone_MultipleLines               3    object              0
9    internet_InternetService               3    object              0
10    internet_OnlineSecurity               3    object              0
11      internet_OnlineBackup               3    object              0
12  internet_DeviceProtection               3    object              0
13       internet_TechSupport               3    object              0
14       internet_StreamingTV               3    object              0
15   internet_StreamingMovies               3    object              0
16           account_Contract               3    object              0
17   account_PaperlessBilling               2    object              0
18      account_PaymentMethod               4    object              0
19    account_charges_Monthly            1585   float64              0
20      account_charges_Total            6531    object              0

    Primer_Valor                                    Valores_Ejemplo
0     0002-ORFBO                              7267 valores (muchos)
1             No                                    ['No' 'Yes' '']
2         Female                                  ['Female' 'Male']
3              0                                              [0 1]
4            Yes                                       ['Yes' 'No']
5            Yes                                       ['Yes' 'No']
6              9                                73 valores (muchos)
7            Yes                                       ['Yes' 'No']
8             No                    ['No' 'Yes' 'No phone service']
9            DSL                         ['DSL' 'Fiber optic' 'No']
10            No                 ['No' 'Yes' 'No internet service']
11           Yes                 ['Yes' 'No' 'No internet service']
12            No                 ['No' 'Yes' 'No internet service']
13           Yes                 ['Yes' 'No' 'No internet service']
14           Yes                 ['Yes' 'No' 'No internet service']
15            No                 ['No' 'Yes' 'No internet service']
16      One year           ['One year' 'Month-to-month' 'Two year']
17           Yes                                       ['Yes' 'No']
18  Mailed check  ['Mailed check' 'Electronic check' 'Credit car...
19          65.6                              1585 valores (muchos)
20         593.3                              6531 valores (muchos)

#🔧 Transformación

#📊 Carga y análisis

#📄Informe final